version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - vue3-volume:/app/node_modules
      - .:/app/
    
    command: /bin/sh -c "yarn install && yarn run serve"

    stdin_open: true
    tty: true

volumes:
  vue3-volume:
